title: GitHub Study
author: HDUD
email: hdud826@naver.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Study용

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  hdud826 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
